tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
  
  certificates:
    - certFile: /etc/traefik/certificates/local-cert.pem
      keyFile: /etc/traefik/certificates/local-key.pem
