---
theme: light
jwt_secret: a_very_important_secret
default_redirection_url: http://localhost:3000

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug
  format: text
  file_path: /config/authelia.log

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

session:
  name: authelia_session
  domain: localhost
  secret: unsecure_session_secret
  expiration: 3600
  inactivity: 300
  redis:
    host: redis
    port: 6379

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

access_control:
  default_policy: deny
  rules:
    - domain: localhost
      policy: bypass
    - domain: "localhost:3000"
      policy: two_factor

notifier:
  filesystem:
    filename: /config/notification.txt 