---
theme: light
identity_validation:
  reset_password:
    jwt_secret: a_very_long_secret_key_that_is_at_least_32_characters_long

server:
  address: tcp://0.0.0.0:9091

log:
  level: debug
  format: text
  file_path: /config/authelia.log

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

session:
  name: authelia_session
  secret: another_very_long_secret_key_that_is_at_least_32_characters_long
  expiration: 3600  # 1 hour
  inactivity: 300   # 5 minutes
  remember_me: true
  domain: 127.0.0.1

access_control:
  default_policy: deny
  rules:
    - domain: "127.0.0.1"
      policy: one_factor
      resources:
        - "/*"

storage:
  encryption_key: yet_another_very_long_secret_key_that_is_at_least_32_characters_long
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt 